### ISSUE TITLE
Next Launch not updating

### ISSUE THREAD

**Issue by netnutmike** [djtimca/HASpaceX#43] opened 2022-06-16 19:20 UTC
I noticed today (June 16th) that the next launch says June 1st.  There are 3 launches this weekend so it should be June 17th.  Even the countdown timer is now -15 days.

I tried reloading the integration and even restarting home assistant.  The last launch seems to be updating ok, just not the next launch.

**Comment by djtimca** [comment] 2022-06-16 21:30
Duplicate of #42

The integration is reporting the data from the source API correctly. Periodically the API does not return current info. It should correct itself at some point.

**Closed as not planned** 2022-06-16 21:30 UTC

**Comment by netnutmike** [comment] 2022-06-16 21:40
I see, the problem is on the SpaceX side :). Even the upcoming launches has some good and old info in it.
